#!/bin/bash

packages=(
	"i3-gaps"
	"tint2"
	"i3lock"
	"kitty"
	"dolphin"
	"gthumb"
	"firefox"
	"bluez"
	"bluez-utils"
	"timeshift"
	"github-cli"
)

for package in "${packages[@]}"; do
    slashes
    if confirm "Do you want to install $package? (y/n)" "Installing $package." "Skipping $package." "y/n"; then
        echo "Installing $package..."
        yay -S --noconfirm "$package"
        if [ $? -ne 0 ]; then
            echo "Failed to install $package."
        else
            echo "$package installed successfully."
        fi
    fi
done
